/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as twitterSol from "./Twitter.sol";
export type { twitterSol };
export type { Profile } from "./Profile";
