/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProfile__factory } from "./IProfile__factory";
export { Twitter__factory } from "./Twitter__factory";
